---
model_list:
  - model_name: "openrouter/*"
    litellm_params:
      model: "openrouter/*"
      api_key: "os.environ/OPENROUTER_KEY"
      organization:
        - "org-1"
        - "org-2"
        - "org-3"

general_settings:
  master_key: sk-1234 
  database_url: "postgresql://postgres:password@localhost/"
